---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Oracle Linux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package and php in ubuntu
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php package in oracle linux
    tags: httpd, apache, oraclelinux
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: copy default html file to site
    tags: httpd, apache, apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package: 
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (OracleLinux)
    tags: mariadb, db, oraclelinux
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: install mariadb package (Ubuntu)
    tags: ubuntu, mariadb, db
    apt:
      name: mariadb_server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba, file
      package:
        name: samba
        state: latest










